---
# pre-commit hook catalog -> https://pre-commit.com/hooks.html
# Manually run all pre-commit checks with:
#    `pre-commit autoupdate`
#    `pre-commit run --all-files`
#
# Manually ignore pre-commit checks with --no-verify...
#    `git commit --no-verify <filepath> -m "Some message here"
repos:

  # auto-format code for the --pyXXXXXXX argument.
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: ["--py3-plus"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the ref you want to point at
    hooks:
    - id: python-no-eval
    - id: rst-backticks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-yaml
    - id: check-json
    - id: check-docstring-first # Forbid code before a function's docstring
    - id: check-symlinks                        # Look for isolated symlinks
    - id: check-shebang-scripts-are-executable  # Fix permissions on scripts
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: fix-byte-order-marker
    - id: trailing-whitespace
    - id: end-of-file-fixer
      #- id: no-commit-to-branch   # By default, protect 'master' and 'main'

    # https://github.com/pre-commit/pre-commit-hooks/issues/106
    - id: fix-encoding-pragma   # Remove "# -*- coding: utf-8 -*-" from files
      args: ['--remove']        #    Python3 doesn't need the utf8 pragma
