---
# Documentation reference
#     https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository
#
# The titles of markdown (*.md) files in `.github/ISSUE_TEMPLATE/*.md`
# determine what buttons are shown when opening a github issue...
#
# yaml formatting checked with http://www.yamllint.com/
#
blank_issues_enabled: false
contact_links:
  - name: "Security issue"
    url: penningtonthing@gmail.com
    about: "Do not report security issues publicly. Please email our security contact."
  - name: Questions
    url: https://stackoverflow.com/questions/ask?title=How%20do%20I&tags=ciscoconfparse+python
    about: "StackOverflow or reddit/r/Python are good places to ask programming questions, such as those involving CiscoConfParse(). We do not support python programming questions here."
